// <auto-generated />
using System;
using BackendAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250312164135_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendAPI.Models.BillOfMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildComponentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ParentComponentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChildComponentId");

                    b.HasIndex("MachineId");

                    b.HasIndex("ParentComponentId");

                    b.ToTable("BillOfMaterials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChildComponentId = 2,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1750),
                            IsDeleted = false,
                            Level = 1,
                            MachineId = 1,
                            Notes = "ลูกปืนสำหรับมอเตอร์หลัก",
                            ParentComponentId = 1,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 2,
                            ChildComponentId = 4,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1760),
                            IsDeleted = false,
                            Level = 1,
                            MachineId = 1,
                            Notes = "สายพานขับเคลื่อนหลัก",
                            ParentComponentId = 1,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 3,
                            ChildComponentId = 5,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1760),
                            IsDeleted = false,
                            Level = 1,
                            MachineId = 2,
                            Notes = "เซ็นเซอร์สำหรับระบบควบคุม",
                            ParentComponentId = 7,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 4,
                            ChildComponentId = 9,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1760),
                            IsDeleted = false,
                            Level = 1,
                            MachineId = 3,
                            Notes = "ซีลสำหรับระบบไฮดรอลิก",
                            ParentComponentId = 8,
                            Quantity = 4m
                        },
                        new
                        {
                            Id = 5,
                            ChildComponentId = 3,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1760),
                            IsDeleted = false,
                            Level = 1,
                            MachineId = 4,
                            Notes = "วาล์วควบคุมระบบนิวเมติก",
                            ParentComponentId = 7,
                            Quantity = 6m
                        },
                        new
                        {
                            Id = 6,
                            ChildComponentId = 10,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1770),
                            IsDeleted = false,
                            Level = 1,
                            MachineId = 5,
                            Notes = "สกรูบอลล์สำหรับระบบเคลื่อนที่",
                            ParentComponentId = 1,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 7,
                            ChildComponentId = 6,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1770),
                            IsDeleted = false,
                            Level = 1,
                            MachineId = 6,
                            Notes = "กระบอกลมสำหรับระบบคีบชิ้นงาน",
                            ParentComponentId = 8,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 8,
                            ChildComponentId = 5,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1770),
                            IsDeleted = false,
                            Level = 1,
                            MachineId = 7,
                            Notes = "เซ็นเซอร์สำหรับระบบวัด",
                            ParentComponentId = 7,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 9,
                            ChildComponentId = 4,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1770),
                            IsDeleted = false,
                            Level = 1,
                            MachineId = 8,
                            Notes = "สายพานลำเลียง",
                            ParentComponentId = 1,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 10,
                            ChildComponentId = 10,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1770),
                            IsDeleted = false,
                            Level = 1,
                            MachineId = 9,
                            Notes = "สกรูบอลล์สำหรับระบบเคลื่อนที่แกน XYZ",
                            ParentComponentId = 7,
                            Quantity = 3m
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1530),
                            Description = "Electrical components and parts",
                            IsDeleted = false,
                            Name = "Electrical"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1530),
                            Description = "Mechanical components and parts",
                            IsDeleted = false,
                            Name = "Mechanical"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1530),
                            Description = "Hydraulic components and systems",
                            IsDeleted = false,
                            Name = "Hydraulic"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1540),
                            Description = "Pneumatic components and systems",
                            IsDeleted = false,
                            Name = "Pneumatic"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1540),
                            Description = "Electronic components and circuits",
                            IsDeleted = false,
                            Name = "Electronic"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1540),
                            Description = "Structural components and frames",
                            IsDeleted = false,
                            Name = "Structural"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1540),
                            Description = "Bolts, nuts, screws and other fasteners",
                            IsDeleted = false,
                            Name = "Fasteners"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1540),
                            Description = "Ball bearings, roller bearings and bushings",
                            IsDeleted = false,
                            Name = "Bearings"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1540),
                            Description = "Gaskets, O-rings and sealing components",
                            IsDeleted = false,
                            Name = "Seals"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1540),
                            Description = "Electric motors and actuators",
                            IsDeleted = false,
                            Name = "Motors"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeadTime")
                        .HasColumnType("int");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1700),
                            Description = "มอเตอร์ไฟฟ้า 3 เฟส 5 แรงม้า 380V",
                            ImageUrl = "/images/components/mtr-3p-5hp.jpg",
                            IsDeleted = false,
                            LeadTime = 14,
                            MinimumStock = 2,
                            Name = "มอเตอร์ไฟฟ้า 3 เฟส 5HP",
                            PartNumber = "MTR-3P-5HP",
                            Price = 12500.00m,
                            SupplierId = 3,
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1700),
                            Description = "ลูกปืนตุ๊กตาเสื้อสี่เหลี่ยม รุ่น UCF205",
                            ImageUrl = "/images/components/brg-ucf205.jpg",
                            IsDeleted = false,
                            LeadTime = 7,
                            MinimumStock = 10,
                            Name = "ลูกปืนตุ๊กตา UCF205",
                            PartNumber = "BRG-UCF205",
                            Price = 850.00m,
                            SupplierId = 2,
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1700),
                            Description = "โซลินอยด์วาล์วควบคุมลม 24VDC 1/4 นิ้ว",
                            ImageUrl = "/images/components/vlv-sl-24dc.jpg",
                            IsDeleted = false,
                            LeadTime = 10,
                            MinimumStock = 5,
                            Name = "โซลินอยด์วาล์ว 24VDC",
                            PartNumber = "VLV-SL-24DC",
                            Price = 1200.00m,
                            SupplierId = 6,
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1710),
                            Description = "สายพานไทม์มิ่ง HTD5M กว้าง 25mm",
                            ImageUrl = "/images/components/blt-htd5m.jpg",
                            IsDeleted = false,
                            LeadTime = 5,
                            MinimumStock = 3,
                            Name = "สายพานไทม์มิ่ง HTD5M",
                            PartNumber = "BLT-HTD5M-25",
                            Price = 450.00m,
                            SupplierId = 1,
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1710),
                            Description = "เซ็นเซอร์วัดระยะทางแบบเลเซอร์ ระยะ 10-100cm",
                            ImageUrl = "/images/components/sns-dist-01.jpg",
                            IsDeleted = false,
                            LeadTime = 21,
                            MinimumStock = 2,
                            Name = "เซ็นเซอร์วัดระยะทาง",
                            PartNumber = "SNS-DIST-01",
                            Price = 2800.00m,
                            SupplierId = 7,
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1710),
                            Description = "กระบอกลมขนาด 32mm ระยะชัก 100mm พร้อมเซ็นเซอร์",
                            ImageUrl = "/images/components/cyl-32-100.jpg",
                            IsDeleted = false,
                            LeadTime = 14,
                            MinimumStock = 3,
                            Name = "กระบอกลมพร้อมเซ็นเซอร์",
                            PartNumber = "CYL-32-100",
                            Price = 3500.00m,
                            SupplierId = 6,
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1720),
                            Description = "ชุดควบคุม PLC พร้อมโมดูล I/O",
                            ImageUrl = "/images/components/plc-cp1l.jpg",
                            IsDeleted = false,
                            LeadTime = 30,
                            MinimumStock = 1,
                            Name = "ชุดควบคุม PLC",
                            PartNumber = "PLC-CP1L",
                            Price = 15000.00m,
                            SupplierId = 7,
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1720),
                            Description = "ปั๊มไฮดรอลิกแรงดันสูง 80 บาร์",
                            ImageUrl = "/images/components/pmp-hyd-80.jpg",
                            IsDeleted = false,
                            LeadTime = 45,
                            MinimumStock = 1,
                            Name = "ปั๊มไฮดรอลิก",
                            PartNumber = "PMP-HYD-80",
                            Price = 22000.00m,
                            SupplierId = 4,
                            UnitOfMeasureId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1720),
                            Description = "ชุดซีลไฮดรอลิกสำหรับกระบอกขนาด 32mm",
                            ImageUrl = "/images/components/seal-hyd-32.jpg",
                            IsDeleted = false,
                            LeadTime = 7,
                            MinimumStock = 10,
                            Name = "ชุดซีลไฮดรอลิก",
                            PartNumber = "SEAL-HYD-32",
                            Price = 450.00m,
                            SupplierId = 9,
                            UnitOfMeasureId = 9
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1730),
                            Description = "สกรูบอลล์เกรด C7 ขนาด 16mm พิตช์ 5mm ยาว 500mm",
                            ImageUrl = "/images/components/scw-1605-500.jpg",
                            IsDeleted = false,
                            LeadTime = 21,
                            MinimumStock = 2,
                            Name = "สกรูบอลล์ 1605 ยาว 500mm",
                            PartNumber = "SCW-1605-500",
                            Price = 4500.00m,
                            SupplierId = 5,
                            UnitOfMeasureId = 1
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1640),
                            Description = "เครื่องกลึง CNC ความแม่นยำสูง",
                            ImageUrl = "/images/machines/tl-1500.jpg",
                            InstallationDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "แผนกผลิต A",
                            ManufactureDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Manufacturer = "Thai CNC Machines",
                            ModelNumber = "TL-1500",
                            Name = "เครื่องกลึง CNC รุ่น TL-1500",
                            SerialNumber = "TL1500-2023-001"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1640),
                            Description = "เครื่องกัด CNC 5 แกน สำหรับงานซับซ้อน",
                            ImageUrl = "/images/machines/vm-5x.jpg",
                            InstallationDate = new DateTime(2022, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "แผนกผลิต B",
                            ManufactureDate = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Manufacturer = "Vertical Milling Co., Ltd.",
                            ModelNumber = "VM-5X",
                            Name = "เครื่องกัด CNC 5 แกน",
                            SerialNumber = "VM5X-2022-042"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1650),
                            Description = "เครื่องฉีดพลาสติกขนาด 250 ตัน",
                            ImageUrl = "/images/machines/im-250.jpg",
                            InstallationDate = new DateTime(2021, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "แผนกฉีดพลาสติก",
                            ManufactureDate = new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Manufacturer = "Thai Injection Systems",
                            ModelNumber = "IM-250",
                            Name = "เครื่องฉีดพลาสติก 250 ตัน",
                            SerialNumber = "IM250-2021-103"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1650),
                            Description = "เครื่องเชื่อมหุ่นยนต์อัตโนมัติ",
                            ImageUrl = "/images/machines/rw-200.jpg",
                            InstallationDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "แผนกเชื่อม",
                            ManufactureDate = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Manufacturer = "Robotic Welding Co., Ltd.",
                            ModelNumber = "RW-200",
                            Name = "เครื่องเชื่อมอัตโนมัติ",
                            SerialNumber = "RW200-2023-015"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1650),
                            Description = "เครื่องตัดเลเซอร์กำลังสูง",
                            ImageUrl = "/images/machines/lc-3000.jpg",
                            InstallationDate = new DateTime(2022, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "แผนกตัดแผ่น",
                            ManufactureDate = new DateTime(2022, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Manufacturer = "Laser Cutting Technologies",
                            ModelNumber = "LC-3000",
                            Name = "เครื่องตัดเลเซอร์",
                            SerialNumber = "LC3000-2022-027"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1650),
                            Description = "เครื่องพับโลหะแผ่น CNC",
                            ImageUrl = "/images/machines/pb-120.jpg",
                            InstallationDate = new DateTime(2021, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "แผนกขึ้นรูป",
                            ManufactureDate = new DateTime(2021, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Manufacturer = "Press Brake Systems",
                            ModelNumber = "PB-120",
                            Name = "เครื่องพับโลหะ CNC",
                            SerialNumber = "PB120-2021-058"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1660),
                            Description = "เครื่องทดสอบแรงดึงความแม่นยำสูง",
                            ImageUrl = "/images/machines/ts-50.jpg",
                            InstallationDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "แผนก QC",
                            ManufactureDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Manufacturer = "Testing Equipment Co., Ltd.",
                            ModelNumber = "TS-50",
                            Name = "เครื่องทดสอบแรงดึง",
                            SerialNumber = "TS50-2023-007"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1660),
                            Description = "เครื่องบรรจุภัณฑ์อัตโนมัติ",
                            ImageUrl = "/images/machines/pk-500.jpg",
                            InstallationDate = new DateTime(2022, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "แผนกบรรจุภัณฑ์",
                            ManufactureDate = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Manufacturer = "Packaging Systems",
                            ModelNumber = "PK-500",
                            Name = "เครื่องบรรจุอัตโนมัติ",
                            SerialNumber = "PK500-2022-031"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1660),
                            Description = "เครื่องพิมพ์ 3 มิติสำหรับงานอุตสาหกรรม",
                            ImageUrl = "/images/machines/3dp-x1.jpg",
                            InstallationDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "แผนกต้นแบบ",
                            ManufactureDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Manufacturer = "3D Printing Solutions",
                            ModelNumber = "3DP-X1",
                            Name = "เครื่องพิมพ์ 3 มิติ",
                            SerialNumber = "3DPX1-2023-022"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1670),
                            Description = "เครื่องวัดขนาดความแม่นยำสูง",
                            ImageUrl = "/images/machines/cmm-500.jpg",
                            InstallationDate = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "แผนกตรวจสอบ",
                            ManufactureDate = new DateTime(2022, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Manufacturer = "Coordinate Measuring Co., Ltd.",
                            ModelNumber = "CMM-500",
                            Name = "เครื่องวัดขนาด CMM",
                            SerialNumber = "CMM500-2022-019"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 ถนนสุขุมวิท กรุงเทพฯ 10110",
                            ContactPerson = "สมชาย ใจดี",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1570),
                            Email = "contact@thaiindustrial.com",
                            IsDeleted = false,
                            Name = "Thai Industrial Supply Co., Ltd.",
                            Notes = "ผู้จัดจำหน่ายอุปกรณ์อุตสาหกรรมรายใหญ่",
                            Phone = "02-123-4567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 ถนนพระราม 9 กรุงเทพฯ 10320",
                            ContactPerson = "วิชัย รักดี",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1570),
                            Email = "sales@bangkokbearing.com",
                            IsDeleted = false,
                            Name = "Bangkok Bearing Co., Ltd.",
                            Notes = "ผู้เชี่ยวชาญด้านแบริ่งและอุปกรณ์ส่งกำลัง",
                            Phone = "02-234-5678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 ถนนเพชรบุรี กรุงเทพฯ 10400",
                            ContactPerson = "นภา แสงทอง",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1580),
                            Email = "info@siamelectric.co.th",
                            IsDeleted = false,
                            Name = "Siam Electric Parts Co., Ltd.",
                            Notes = "จำหน่ายอุปกรณ์ไฟฟ้าและอิเล็กทรอนิกส์",
                            Phone = "02-345-6789"
                        },
                        new
                        {
                            Id = 4,
                            Address = "123 นิคมอุตสาหกรรมอีสเทิร์นซีบอร์ด ระยอง 21140",
                            ContactPerson = "ประสิทธิ์ มั่นคง",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1580),
                            Email = "sales@easternhydraulics.com",
                            IsDeleted = false,
                            Name = "Eastern Hydraulics Ltd.",
                            Notes = "ผู้เชี่ยวชาญระบบไฮดรอลิก",
                            Phone = "038-123-456"
                        },
                        new
                        {
                            Id = 5,
                            Address = "101 ถนนบางนา-ตราด กรุงเทพฯ 10260",
                            ContactPerson = "สุรีย์ พรมมา",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1580),
                            Email = "contact@precisiontools.co.th",
                            IsDeleted = false,
                            Name = "Precision Tools Thailand",
                            Notes = "จำหน่ายเครื่องมือความแม่นยำสูง",
                            Phone = "02-456-7890"
                        },
                        new
                        {
                            Id = 6,
                            Address = "234 ถนนเชียงใหม่-ลำพูน เชียงใหม่ 50000",
                            ContactPerson = "ภาณุ ภักดี",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1580),
                            Email = "sales@northernpneumatic.com",
                            IsDeleted = false,
                            Name = "Northern Pneumatic Systems",
                            Notes = "ผู้เชี่ยวชาญระบบนิวเมติก",
                            Phone = "053-234-567"
                        },
                        new
                        {
                            Id = 7,
                            Address = "567 ถนนพระราม 2 กรุงเทพฯ 10150",
                            ContactPerson = "กรรณิการ์ สมใจ",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1580),
                            Email = "info@thaiautomation.com",
                            IsDeleted = false,
                            Name = "Thai Automation Parts Co., Ltd.",
                            Notes = "จำหน่ายอุปกรณ์ระบบอัตโนมัติ",
                            Phone = "02-567-8901"
                        },
                        new
                        {
                            Id = 8,
                            Address = "789 นิคมอุตสาหกรรมมาบตาพุด ระยอง 21150",
                            ContactPerson = "วิทยา ศรีสุข",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1590),
                            Email = "contact@rayongindustrial.com",
                            IsDeleted = false,
                            Name = "Rayong Industrial Supply",
                            Notes = "ผู้จัดจำหน่ายในพื้นที่ EEC",
                            Phone = "038-345-678"
                        },
                        new
                        {
                            Id = 9,
                            Address = "890 ถนนพัฒนาการ กรุงเทพฯ 10250",
                            ContactPerson = "มานะ รักษ์ดี",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1600),
                            Email = "sales@centralseals.co.th",
                            IsDeleted = false,
                            Name = "Central Seals & Gaskets",
                            Notes = "ผู้เชี่ยวชาญด้านซีลและปะเก็น",
                            Phone = "02-678-9012"
                        },
                        new
                        {
                            Id = 10,
                            Address = "321 ถนนรัชดาภิเษก กรุงเทพฯ 10400",
                            ContactPerson = "สมศรี ใจเย็น",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1600),
                            Email = "info@thaimotors.com",
                            IsDeleted = false,
                            Name = "Thai Motor Solutions",
                            Notes = "จำหน่ายมอเตอร์และอุปกรณ์ขับเคลื่อน",
                            Phone = "02-789-0123"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "pc",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1420),
                            IsDeleted = false,
                            Name = "Piece"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "kg",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1420),
                            IsDeleted = false,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "m",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1420),
                            IsDeleted = false,
                            Name = "Meter"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "L",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1420),
                            IsDeleted = false,
                            Name = "Liter"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "mm",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1420),
                            IsDeleted = false,
                            Name = "Millimeter"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "cm",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1420),
                            IsDeleted = false,
                            Name = "Centimeter"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "m²",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1430),
                            IsDeleted = false,
                            Name = "Square Meter"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "m³",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1430),
                            IsDeleted = false,
                            Name = "Cubic Meter"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "set",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1430),
                            IsDeleted = false,
                            Name = "Set"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "roll",
                            CreatedAt = new DateTime(2025, 3, 12, 16, 41, 34, 960, DateTimeKind.Utc).AddTicks(1430),
                            IsDeleted = false,
                            Name = "Roll"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.BillOfMaterial", b =>
                {
                    b.HasOne("BackendAPI.Models.Component", "ChildComponent")
                        .WithMany("ParentBOMs")
                        .HasForeignKey("ChildComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.Machine", "Machine")
                        .WithMany("BillOfMaterials")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackendAPI.Models.Component", "ParentComponent")
                        .WithMany("ChildBOMs")
                        .HasForeignKey("ParentComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildComponent");

                    b.Navigation("Machine");

                    b.Navigation("ParentComponent");
                });

            modelBuilder.Entity("BackendAPI.Models.Component", b =>
                {
                    b.HasOne("BackendAPI.Models.Category", "Category")
                        .WithMany("Components")
                        .HasForeignKey("CategoryId");

                    b.HasOne("BackendAPI.Models.Supplier", "Supplier")
                        .WithMany("Components")
                        .HasForeignKey("SupplierId");

                    b.HasOne("BackendAPI.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("Components")
                        .HasForeignKey("UnitOfMeasureId");

                    b.Navigation("Category");

                    b.Navigation("Supplier");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("BackendAPI.Models.Category", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("BackendAPI.Models.Component", b =>
                {
                    b.Navigation("ChildBOMs");

                    b.Navigation("ParentBOMs");
                });

            modelBuilder.Entity("BackendAPI.Models.Machine", b =>
                {
                    b.Navigation("BillOfMaterials");
                });

            modelBuilder.Entity("BackendAPI.Models.Supplier", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("BackendAPI.Models.UnitOfMeasure", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
